apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-crud
  labels:
    app: drf-crud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drf-crud
  template:
    metadata:
      labels:
        app: drf-crud
    spec:
      containers:
        - name: drf-crud
          imagePullPolicy: IfNotPresent
          image: medmiskini/drf-crud
          ports:
          - containerPort: 8000